POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"sabrina@mail.com",
    "password":"password123"
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"sabrina@mail.com",
    "password":"password123"
}

###
GET http://localhost:3000/whoami
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InNhYnJpbmEiLCJlbWFpbCI6InNhYnJpbmFAbWFpbC5jb20iLCJpYXQiOjE2ODI2OTI2MDh9.VneW1WUp6Cupqe2H4zdYwwc18Ows-8OXnjd1nd1vTCY 

##############################################################

// Home
GET http://localhost:3000

// airlines
### Get all airlines
GET http://localhost:3000/airlines

### Get detail airlines
GET http://localhost:3000/airlines/1

### Create airlines data
POST http://localhost:3000/airlines
Content-Type: application/json

{
    "name": "Lion Air",
    "company": "PT Lion Mentari Airports",
    "total_seet": "215"
}


### Update airlines data
PUT http://localhost:3000/airlines/1
Content-Type: application/json

{
    "name": "Lion Air",
    "company": "PT Lion Mentari Airports",
    "total_seet": "215"
}

### Delete airlines data
DELETE  http://localhost:3000/airlines/2

##############################################################

// airports
### Get all airports
GET http://localhost:3000/airports

### Get detail airports
GET http://localhost:3000/airports/1

### Create airports data
POST http://localhost:3000/airports
Content-Type: application/json

{
    "name": "Kualanamu",
    "city": "Medan",
    "state": "Indonesia",
    "airport_type": "Airbus",
    "code": "330-900 NEO"
}

### Update airports data
PUT http://localhost:3000/airports/1
Content-Type: application/json

{
    "name": "Kualanamu",
    "city": "Medan",
    "state": "Indonesia",
    "airport_type": "Airbus",
    "code": "330-900 NEO"
}

### Delete airports data
DELETE  http://localhost:3000/airports/2

##############################################################

// flight_schedulles
### Get all flight_schedulles
GET http://localhost:3000/flight_schedulles

### Get detail flight_schedulles
GET http://localhost:3000/flight_schedulles/1

### Create flight_schedulles data
POST http://localhost:3000/flight_schedulles
Content-Type: application/json

{
    "airline_id": "1",
    "departure_time": 20.00,
    "arrival_time": 22.00,
    "departure_airport_id": 1,
    "arrival_airport_id": 2
}

### Update flight_schedulles data
PUT http://localhost:3000/flight_schedulles/1
Content-Type: application/json

{
    "airline_id": "1",
    "departure_time": 20.00,
    "arrival_time": 22.00,
    "departure_airport_id": "1",
    "arrival_airport_id": "2"
}

### Delete flight_schedulles data
DELETE  http://localhost:3000/flight_schedulles/2

##############################################################

// flight_prices
### Get all flight_prices
GET http://localhost:3000/flight_prices

### Get detail flight_prices
GET http://localhost:3000/flight_prices/1

### Create flight_prices data
POST http://localhost:3000/flight_prices
Content-Type: application/json

{
    "schedulle_id": "1",
    "class_id": "1",
    "price": "1500000"
}

### Update flight_prices data
PUT http://localhost:3000/flight_prices/1
Content-Type: application/json

{
    "schedulle_id": "1",
    "class_id": "1",
    "price": "1500000"
}

### Delete flight_prices data
DELETE  http://localhost:3000/flight_prices/2

##############################################################

// seat_classs
### Get all seat_classs
GET http://localhost:3000/seat_classs

### Get detail seat_classs
GET http://localhost:3000/seat_classs/1

### Create seat_classs data
POST http://localhost:3000/seat_classs
Content-Type: application/json

{
    "name": "Economy",
    "description": "Economy Class"
}

### Update seat_classs data
PUT http://localhost:3000/seat_classs/1
Content-Type: application/json

{
    "name": "Economy",
    "description": "Economy Class"
}

### Delete seat_classs data
DELETE  http://localhost:3000/seat_classs/2