POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"daffaammar09@gmail.com",
    "phone" : "018921312312",
    "password":"password"
}

### 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"sabrina@mail.com",
    "password":"password123"
}

###
POST http://localhost:3000/flight_schedulles
Content-Type: application/json

{
    "airplane_id" : 5,
    "departure_time" : "2023-06-12T12:32:14.000Z",
    "arrival_time" : "2023-06-12T15:32:14.000Z",
    "departure_airport_id" : 1,
    "arrival_airport_id" : 4,
    "flight_number" : "ABCS",
    "free_baggage" : 20,
    "cabin_baggage" : 15,
    "price" : 1000000,
    "class_id" : 1,
    "departure_terminal_name" : "Terminal 2B",
    "arrival_terminal_name" : "Terminal Domestik"
}

###
GET http://localhost:3000/whoami

